### ISSUE TITLE
RSS但返回结果内容不含标题

### ISSUE THREAD

**Issue by felinae98** [felinae98/nonebot-hk-reporter#15]
想要通过rss订阅 https://rsshub.app/anigamer/new_anime 来获取番剧更新列表，但返回结果内容不含标题。
希望rss订阅功能可以同时获取标题

_Originally posted by @xana278 in https://github.com/felinae98/nonebot-hk-reporter/issues/14#issuecomment-873635820_

**Comment by felinae98** [comment]
@xana278 标题是指`<title>動畫瘋最後更新</title>`吗

**Comment by xana278** [comment]
这是用Reeder的预览图
![CleanShot 2021-07-06 at 20 26 38](https://user-images.githubusercontent.com/71873002/124599637-77b9e980-de98-11eb-9653-664068559894.png)
期望效果：显示番名标题和正文内容 效果可参考上图
实际效果：只显示 `動畫瘋最後更新` 和 `07/04 更新至 [1]`
