### ISSUE TITLE
能不能让机器人的主人也可以触发指令

### ISSUE THREAD

**Issue by djkcyl** [felinae98/nonebot-hk-reporter#4]
我作为一个机器人的主人居然不能操作她，气抖冷（

**Comment by djkcyl** [comment]
然后是，，有点没明白命令要怎么触发

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/120069094-ac2ad080-c0b6-11eb-920b-f4bae02b8b4b.png)

**Comment by sam01101** [comment]
Hi, #633

https://docs.go-cqhttp.org/guide/config.html#%E9%85%8D%E7%BD%AE%E4%BF%A1%E6%81%AF
![image](https://user-images.githubusercontent.com/25792361/120073857-b48e0600-c0cc-11eb-8b34-92cd249862e8.png)
`report-self-message` 启用就可以接收机器人自身发的信息
__注意`message type`会和本身的不一样, 还有`gocq`发送的也会照样上报__
__小心别整Recursion了__

**Comment by djkcyl** [comment]
机器人现在是可以接受到消息的，就是，，，不知道命令怎么触发

**Comment by sam01101** [comment]
> 机器人现在是可以接受到消息的，就是，，，不知道命令怎么触发

和正常人一样发

**Comment by djkcyl** [comment]
> > 机器人现在是可以接受到消息的，就是，，，不知道命令怎么触发
> 
> 和正常人一样发, 额外添加一个event获取

可能我的表达有误吧，，，我想说的是
如果我要订阅一个b站up
那我应该在群里发什么指令呢
还有就是，如果我不是管理员或群主，我能否通过其他方法控制bot的订阅

**Comment by felinae98** [comment]
https://github.com/felinae98/nonebot-hk-reporter/issues/4#issuecomment-850819660 
这个bug在最新版修复了

**Comment by felinae98** [comment]
https://v2.nonebot.dev/api/config.html#superusers
在这里设置超级用户的QQ号，超级用户和群主群管理都可以管理机器人
